project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
    - artist-datamodel.qmd
    - exhibition-datamodel.qmd
    - dnb-catalogue-datamodel.qmd
    - item-in-exhibition-datamodel.qmd

metadata:
  author:
    - name: Hong An Dinh
      orcid: 0009-0004-5752-0370
      email: hong-an.dinh@stud.hs-hannover.de

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: artist-datamodel.qmd
        text: Künstler-Datenmodell
      - href: exhibition-datamodel.qmd
        text: Ausstellungs-Datenmodell
      - href: dnb-catalogue-datamodel.qmd
        text: DNB-Katalog-Datenmodell 
      - href: item-in-exhibition-datamodel.qmd
        text: Objekt im Ausstellungs-Datenmodell
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
